version: '3.7'
services:
  nginx:
    container_name: "django-app-nginx"
    image: nginx:1.25.1-alpine
    volumes:
      - ./nginx.docker.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "80:80"
    depends_on:
      - web
  redis:
    container_name: "django-app-redis"
    image: redis:alpine
  celery:
    container_name: "django-app-celery"
    build:
      context: .
      args:
        - 'FURY_AUTH=${FURY_AUTH}'
    command: >
      sh -c "celery -A django_app worker -l info"
    volumes:
      - .:/app
    depends_on:
      - db
      - redis
      - web
  web:
    container_name: "django-app-web"
    build:
      context: .
      args:
        - 'FURY_AUTH=${FURY_AUTH}'
    command: >
      sh -c "python manage.py migrate &&
             gunicorn django_app.wsgi:application --bind 0.0.0.0:5000 --reload"
    volumes:
     - .:/app
    depends_on:
     - db
  db:
    container_name: "django-app-db"
    image: postgres:15.5-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=pg
    ports:
      - "5433:5432"
volumes:
  static_volume:
  postgres_data:
