FROM python:3
ENV PYTHONDONTWRITEBYTECODE=1
ENV PYTHONUNBUFFERED=1
ARG FURY_AUTH
WORKDIR /app
COPY . /app
RUN pip install -r requirements.txt --extra-index-url=https://$FURY_AUTH:@pypi.fury.io/hutfortytwo/